2023-12-05 18:42:01,665 [ERROR]: row value misused in /Users/chelseanieves/FortuneTeller/Fortune-Teller-1/databasehelper.py:347
2023-12-05 18:42:15,733 [ERROR]: row value misused in /Users/chelseanieves/FortuneTeller/Fortune-Teller-1/databasehelper.py:347
2023-12-06 08:27:53,747 [ERROR]: row value misused in /Users/chelseanieves/FortuneTeller/Fortune-Teller-4/databasehelper.py:347
2023-12-07 14:34:08,864 [ERROR]: UNIQUE constraint failed: user.userId in /Users/chelseanieves/7Dec/Fortune-Teller/databasehelper.py:309
2023-12-07 14:34:24,265 [ERROR]: UNIQUE constraint failed: user.userId in /Users/chelseanieves/7Dec/Fortune-Teller/databasehelper.py:309
2023-12-08 09:22:22,929 [ERROR]: no such table: user in /Users/chelseanieves/7Dec/Fortune-Teller-2/databasehelper.py:173
2023-12-08 09:35:19,350 [ERROR]: no such table: user in /Users/chelseanieves/7Dec/Fortune-Teller-2/databasehelper.py:173
2023-12-08 09:35:19,351 [ERROR]: no such table: user in /Users/chelseanieves/7Dec/Fortune-Teller-2/databasehelper.py:127
2023-12-08 09:35:19,351 [ERROR]: no such table: user in /Users/chelseanieves/7Dec/Fortune-Teller-2/databasehelper.py:173
2023-12-08 09:35:19,691 [ERROR]: no such table: user in /Users/chelseanieves/7Dec/Fortune-Teller-2/databasehelper.py:320
2023-12-08 09:35:19,692 [ERROR]: no such table: user in /Users/chelseanieves/7Dec/Fortune-Teller-2/databasehelper.py:56
2023-12-08 09:35:53,724 [ERROR]: no such table: user in /Users/chelseanieves/7Dec/Fortune-Teller-2/databasehelper.py:173
2023-12-08 09:35:53,724 [ERROR]: no such table: user in /Users/chelseanieves/7Dec/Fortune-Teller-2/databasehelper.py:127
2023-12-08 09:35:53,725 [ERROR]: no such table: user in /Users/chelseanieves/7Dec/Fortune-Teller-2/databasehelper.py:173
2023-12-08 09:35:54,064 [ERROR]: no such table: user in /Users/chelseanieves/7Dec/Fortune-Teller-2/databasehelper.py:320
2023-12-08 09:35:54,065 [ERROR]: no such table: user in /Users/chelseanieves/7Dec/Fortune-Teller-2/databasehelper.py:56
2023-12-08 09:37:08,178 [ERROR]: no such table: user in /Users/chelseanieves/7Dec/Fortune-Teller-2/databasehelper.py:173
2023-12-08 09:37:08,179 [ERROR]: no such table: user in /Users/chelseanieves/7Dec/Fortune-Teller-2/databasehelper.py:127
2023-12-08 09:37:08,180 [ERROR]: no such table: user in /Users/chelseanieves/7Dec/Fortune-Teller-2/databasehelper.py:173
2023-12-08 09:37:08,520 [ERROR]: no such table: user in /Users/chelseanieves/7Dec/Fortune-Teller-2/databasehelper.py:320
2023-12-08 09:37:08,520 [ERROR]: no such table: user in /Users/chelseanieves/7Dec/Fortune-Teller-2/databasehelper.py:56
2023-12-08 09:40:26,112 [ERROR]: no such table: user in /Users/chelseanieves/7Dec/Fortune-Teller-2/databasehelper.py:173
2023-12-08 09:40:26,112 [ERROR]: no such table: user in /Users/chelseanieves/7Dec/Fortune-Teller-2/databasehelper.py:127
2023-12-08 09:40:26,113 [ERROR]: no such table: user in /Users/chelseanieves/7Dec/Fortune-Teller-2/databasehelper.py:173
2023-12-08 09:40:26,453 [ERROR]: no such table: user in /Users/chelseanieves/7Dec/Fortune-Teller-2/databasehelper.py:320
2023-12-08 09:40:26,453 [ERROR]: no such table: user in /Users/chelseanieves/7Dec/Fortune-Teller-2/databasehelper.py:56
2023-12-08 09:41:21,851 [ERROR]: no such table: user in /Users/chelseanieves/7Dec/Fortune-Teller-2/databasehelper.py:173
2023-12-08 09:41:21,852 [ERROR]: no such table: user in /Users/chelseanieves/7Dec/Fortune-Teller-2/databasehelper.py:127
2023-12-08 09:41:21,852 [ERROR]: no such table: user in /Users/chelseanieves/7Dec/Fortune-Teller-2/databasehelper.py:173
2023-12-08 09:41:22,192 [ERROR]: no such table: user in /Users/chelseanieves/7Dec/Fortune-Teller-2/databasehelper.py:320
2023-12-08 09:41:22,192 [ERROR]: no such table: user in /Users/chelseanieves/7Dec/Fortune-Teller-2/databasehelper.py:56
2023-12-08 09:42:01,419 [ERROR]: no such table: user in /Users/chelseanieves/7Dec/Fortune-Teller-2/databasehelper.py:127
2023-12-08 09:42:01,420 [ERROR]: no such table: user in /Users/chelseanieves/7Dec/Fortune-Teller-2/databasehelper.py:173
2023-12-08 09:42:01,760 [ERROR]: no such table: user in /Users/chelseanieves/7Dec/Fortune-Teller-2/databasehelper.py:320
2023-12-08 09:42:01,761 [ERROR]: no such table: user in /Users/chelseanieves/7Dec/Fortune-Teller-2/databasehelper.py:56
2023-12-08 09:43:40,798 [ERROR]: no such table: user in /Users/chelseanieves/7Dec/Fortune-Teller-2/databasehelper.py:127
2023-12-08 09:43:40,798 [ERROR]: no such table: user in /Users/chelseanieves/7Dec/Fortune-Teller-2/databasehelper.py:173
2023-12-08 09:43:41,138 [ERROR]: no such table: user in /Users/chelseanieves/7Dec/Fortune-Teller-2/databasehelper.py:320
2023-12-08 09:43:41,138 [ERROR]: no such table: user in /Users/chelseanieves/7Dec/Fortune-Teller-2/databasehelper.py:56
2023-12-08 09:45:47,164 [ERROR]: no such table: user in /Users/chelseanieves/7Dec/Fortune-Teller-2/databasehelper.py:173
